<a href="https://colab.research.google.com/github/ZHANGXIYUAN6/Data-science/blob/main/tutorial3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np

In [11]:
array_2x2 = np.array([[1,2],
            [3,4]])

In [17]:
print("2×2 array:")
print(array_2x2)

2×2 array:
[[1 2]
 [3 4]]


In [14]:
import numpy as np

In [16]:
random_array_3x4 = np.random.rand(3,4)

In [18]:
print("3×4 random array:")
print(random_array_3x4)

3×4 random array:
[[0.37054756 0.79631165 0.331584   0.31590476]
 [0.18632668 0.35034354 0.13409618 0.80245919]
 [0.80297086 0.1694164  0.99272607 0.54751289]]


In [19]:
import numpy as np

In [22]:
ones_array = np.ones((3,3))

In [23]:
zeros_array = np.zeros((3,3))

In [24]:
print("3×3 array of ones:")
print(ones_array)
print("3×3 array of zeros:")
print(zeros_array)

3×3 array of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
3×3 array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [25]:
import numpy as np

In [27]:
random_array_6x3 = np.random.rand(6,3)

In [28]:
transposed_array = random_array_6x3.T

In [30]:
print("orginal random array:")
print(random_array_6x3)
print ("transposed array:")
print(transposed_array)

orginal random array:
[[0.59582812 0.31486871 0.14347451]
 [0.08310904 0.66769423 0.58385071]
 [0.63497215 0.72457501 0.8068744 ]
 [0.54383251 0.22771334 0.37919371]
 [0.86625059 0.96463067 0.20714708]
 [0.1549861  0.17044248 0.58094828]]
transposed array:
[[0.59582812 0.08310904 0.63497215 0.54383251 0.86625059 0.1549861 ]
 [0.31486871 0.66769423 0.72457501 0.22771334 0.96463067 0.17044248]
 [0.14347451 0.58385071 0.8068744  0.37919371 0.20714708 0.58094828]]


In [31]:
import numpy as np

In [33]:
n,p,m=3,4,2
array_np = np.random.rand(n,p)
array_mp = np.random.rand(m,p)
print(array_np)
print(array_mp)

[[0.75048978 0.15596455 0.88273164 0.44830351]
 [0.46641097 0.0470346  0.30687218 0.73824433]
 [0.68907073 0.04233183 0.18240918 0.5908846 ]]
[[0.40124339 0.34377872 0.42359891 0.09179237]
 [0.46656045 0.58827964 0.1601754  0.5570194 ]]
